#!/bin/bash
# play one or more episodes from full catalogue with VLC

if [ $# -ge 1 ]         # if (count) argument passed
then                    # use the value passed
#    vlc $(./rp $1) 2> /dev/null &
     ./rp $1 | tee /dev/tty | xargs vlc 2> /dev/null &
else                    # else default to 1
     ./rp | tee /dev/tty | xargs vlc 2> /dev/null &
fi
