#!/bin/bash
# play one or more new episodes with VLC

if [ $# -ge 1 ]         # if (count) argument passed
then                    # use the value passed
    vlc $(./rpn $1) 2> /dev/null &
else                    # else default to 1
    vlc $(./rpn) 2> /dev/null &
fi