#!/bin/sh
# rp - random podcast
# return one or more random episodes from 
# full episode list, default 1

if [ $# -ge 1 ]         # if (count) argument passed
then                    # use the value passed
    cat podcasts_opml.txt | shuf -n $1
else                    # else default to 1
    cat podcasts_opml.txt | shuf -n 1

fi
