#!/bin/sh
# return one or more random episodes
# from list of newest episodes,
# default 1


if [ $# -ge 1 ]         # if (count) argument passed
then                    # use the value passed
    cat newest.txt | shuf -n $1
else                    # else default to 1
    cat newest.txt | shuf -n 1

fi
