#!/usr/bin/env bash

 python optimized_parser.py PodcastAddict_OPML_export_20250404_220434.opml 30 && ./parse_newest && git add newest.txt PodcastAddict_OPML_export_20250404_220434.txt && git commit -m "auto updated" && git push
